#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       not POSIX-compliant, you may see errors when running this script. You
#       can try using bash by running this script with 'bash gradlew'.
#
#   (2) You need to use the 'sh' shell to run this script on Windows, or you
#       may need to use 'bash gradlew' instead.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls##* }
    app_path=$(readlink "$link")
done

APP_HOME=$(cd "${APP_HOME:-./}" && pwd)

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS -XX:MaxRAMPercentage=75"

# Use the maximum number of parallel build processes
GRADLE_PARALLEL="-Dorg.gradle.parallel=true"

# Use the maximum number of parallel build processes
GRADLE_DAEMON="-Dorg.gradle.daemon=false"

# Use the maximum number of parallel build processes
GRADLE_CACHE="-Dorg.gradle.caching=true"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/bin/java" ] ; then
        JAVA_HOME="$JAVA_HOME/bin/java"
    else
        echo >&2 "JAVA_HOME is not a directory: $JAVA_HOME"
        exit 1
    fi
else
    JAVA_HOME=$(readlink -f $(which java))
    if [ -z "$JAVA_HOME" ] ; then
        echo >&2 "JAVA_HOME not set and no 'java' command found in PATH."
        exit 1
    fi
fi

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS -XX:MaxRAMPercentage=75"

# Use the maximum number of parallel build processes
GRADLE_PARALLEL="-Dorg.gradle.parallel=true"

# Use the maximum number of parallel build processes
GRADLE_DAEMON="-Dorg.gradle.daemon=false"

# Use the maximum number of parallel build processes
GRADLE_CACHE="-Dorg.gradle.caching=true"

GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Increase the heap size for Gradle
GRADLE_OPTS="$GRADLE_OPTS -Xmx2048m -Xms512m"

JAVA_OPTS="$JAVA_OPTS -XX:MaxRAMPercentage=75"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -Xmx2048m -Xms512m"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -XX:MaxRAMPercentage=75"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -Xmx2048m -Xms512m"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -XX:MaxRAMPercentage=75"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

JAVA_OPTS="$JAVA_OPTS -XX:MaxRAMPercentage=75"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -Xmx2048m -Xms512m"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -XX:MaxRAMPercentage=75"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -Xmx2048m -Xms512m"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -XX:MaxRAMPercentage=75"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -Xmx2048m -Xms512m"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -XX:MaxRAMPercentage=75"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -Xmx2048m -Xms512m"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -XX:MaxRAMPercentage=75"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -Xmx2048m -Xms512m"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -XX:MaxRAMPercentage=75"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -Xmx2048m -Xms512m"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -XX:MaxRAMPercentage=75"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -Xmx2048m -Xms512m"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -XX:MaxRAMPercentage=75"

# Increase the heap size for Gradle
JAVA_OPTS="$JAVA_OPTS -Xmx2048m -Xms512m"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLEL $GRADLE_DAEMON $GRADLE_CACHE"

# Use the maximum number of parallel build processes
GRADLE_OPTS="$GRADLE_OPTS $GRADLE_PARALLE